language: php

php:
  - 5.3
  - 5.4

before_script:
  - ./bin/configure_test_env.sh
  - composer install --dev --prefer-source

script:
  - php bin/phpspec run -fpretty --verbose
  - phpunit
