language: php

sudo: true

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - AWS_KEY:
    - AWS_SECRET:
    - AZURE_ACCOUNT:
    - AZURE_KEY:

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

services:
  - mongodb

env:
  - MONGO_URI="mongodb://127.0.0.1:27017"
    MONGO_DBNAME="gridfs_test"
    SFTP_HOST=localhost
    SFTP_USER=gaufrette
    SFTP_PASSWORD=gaufrette
    SFTP_BASE_DIR=/home/gaufrette
    FTP_HOST=localhost
    FTP_USER=gaufrette
    FTP_PASSWORD=gaufrette
    FTP_BASE_DIR=/gaufrette/

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:1} != "hhvm" ]]; then
      echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
      phpenv config-rm xdebug.ini;
    else
      composer require mongofill/mongofill --ignore-platform-reqs;
    fi
  - sudo apt-get update
  - sudo apt-get install -y libssh2-1-dev vsftpd
  - sudo useradd -d /home/./gaufrette gaufrette # Removing "./" from this path would break any further Travis builds
  - echo "gaufrette:gaufrette" | sudo chpasswd
  - sudo mkdir /home/gaufrette /srv/empty
  - sudo chown gaufrette:gaufrette /home/gaufrette /srv/ftp
  - sudo cp .travis/vsftpd.conf /etc/vsftpd.conf
  - sudo service vsftpd restart
  - cp tests/Gaufrette/Functional/adapters/DoctrineDbal.php.dist tests/Gaufrette/Functional/adapters/DoctrineDbal.php -f
  - composer self-update && composer install --prefer-source --no-interaction
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then yes | pecl install ssh2 && composer require herzult/php-ssh; fi

script:
  - php vendor/bin/phpspec run -fpretty --verbose
  - php vendor/bin/phpunit --verbose
