build: false
platform: 'x86'
clone_folder: C:\projects\gaufrette
branches:
  except:
    - gh-pages

cache:
  - '%LOCALAPPDATA%\Composer\files'
  - c:\php -> appveyor.yml

environment:
  AWS_KEY:
    secure: nMVfvhojgVc9VBlrYXeddaYIQHlVAlupWmxNjXMlsB0=
  AWS_SECRET:
    secure: MiAf2q7mnqSIZSoChd9v3pwUrXHeAEpZP8Zc0E0qjiOBXPvplzJVtrkWRwTNlQl3
  AWS_BUCKET: gaufretteci
  RACKSPACE_USER:
    secure: aEIZdm+IXe9dGLOnSmgu8A==
  RACKSPACE_APIKEY:
    secure: CqBlB4EVIM2FMaYxBdplTaQzw8JgKElxYvKYpXUXPHpOdwJcnYy0gk2KdjF4fXDM
  RACKSPACE_CONTAINER: gaufretteci
  AZURE_ACCOUNT:
    secure: s6JCZ8ztVGvVYprceONZOg==
  AZURE_KEY:
    secure: 6+9kd9n/BO65LI8ZCJJXOwo9v5QmMULKWExHgECe+rnflaw+ZiQ8jFfHwxxjOfUF1qulAyxHQmDj7M3Cfvbe/DAASjk52ngEMvHC6wv2/Eo0cBMQiUlS9vPeUlvkUy1L
  AZURE_CONTAINER: gaufretteci
  MONGO_URI: "mongodb://127.0.0.1:27017"
  MONGO_DBNAME: "gridfs_test"

services:
  - mongodb

init:
  - SET PATH=C:\Program Files\OpenSSL;c:\php;%PATH%
  - SET PHP=1

install:
  - IF EXIST c:\php (SET PHP=0) ELSE (mkdir c:\php)
  - cd c:\php
  - IF %PHP%==1 cinst -y OpenSSL.Light --version 1.1.1
  - IF %PHP%==1 curl -fsSL -o php-7.2.12-Win32-VC15-x86.zip https://windows.php.net/downloads/releases/archives/php-7.2.12-Win32-VC15-x86.zip
  - IF %PHP%==1 7z x php-7.2.12-Win32-VC15-x86.zip -y >nul
  - IF %PHP%==1 del /Q *.zip
  - IF %PHP%==1 curl -fsSL -o cacert.pem https://curl.haxx.se/ca/cacert.pem
  - IF %PHP%==1 cd ext
  - IF %PHP%==1 curl -fsSL -o php_mongodb-1.5.3-7.2-ts-vc15-x86.zip https://windows.php.net/downloads/pecl/releases/mongodb/1.5.3/php_mongodb-1.5.3-7.2-ts-vc15-x86.zip
  - IF %PHP%==1 7z x php_mongodb-1.5.3-7.2-ts-vc15-x86.zip php_mongodb.dll -y >nul
  - IF %PHP%==1 del /Q *.zip
  - IF %PHP%==1 cd ..
  - IF %PHP%==1 copy php.ini-production php.ini /Y
  - IF %PHP%==1 echo extension_dir=ext >> php.ini
  - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
  - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
  - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
  - IF %PHP%==1 echo extension=php_mongodb.dll >> php.ini
  - IF %PHP%==1 echo extension=php_pdo_sqlite.dll >> php.ini
  - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
  - IF %PHP%==1 echo extension=php_curl.dll >> php.ini
  - IF %PHP%==1 echo extension=php_ftp.dll >> php.ini
  - IF %PHP%==1 echo openssl.cafile=c:\php\cacert.pem >> php.ini
  - cd C:\projects\gaufrette
  - curl -fsSL -o composer.phar https://getcomposer.org/composer.phar
  - php composer.phar update --prefer-dist --no-interaction --no-progress --no-suggest --ansi

test_script:
  - cd C:\projects\gaufrette
  - vendor\bin\phpspec run -fpretty --verbose
  - vendor\bin\phpunit --verbose -c phpunit.xml.dist
